# Site settings

title: "LGBT MP"

description: "A website that lists the ‘out’ lesbian, gay, bisexual or trans (LGBT) members of the House of Commons in the UK Parliament"

baseurl: "/lgbt-mp" # the subpath of your site, e.g. /blog
url: "http://jrpeart.com"
author: "John Peart"

asset-path: "/assets"
image-path: "/images"
post-images-path: "/featured"
css-path: "/styles"
js-path: "/scripts"

logo: "/site/logo.png"
logo-svg: "/site/logo.svg"
logo-menubar: "/site/menubar.svg"
logo-four-oh-four: "/site/404.svg"
social-media: "/site/social-media.png"
touch: "/site/touch.png"
pinned: "/site/pinned.svg"
pinned-colour: "#b10e1e"

# Social settings
facebook-app-id: "1053585037989505" # For Facebook OpenGraph integration
facebook-profile-id: "100003820028435" # For Facebook OpenGraph integration
facebook-slug: "john.robert.peart" # Automatically pre-pends http://facebook.com/
twitter-username: "johnpeart" # Twitter handle i.e. joebloggs
github-username:  "johnpeart"
google-site-verification: "DaqGCZ6cZIqm7q_nVSnOzjJmFFjbRfW2X7FDzpQDQZk" # GSV code; proves domain ownership

#Analytics
disable-analytics: false # Switch to "false" to start GA logging
google-analytics: "UA-27553664-1" # GA ID code

# Plugins and build settings

permalink: pretty
markdown: kramdown
future: false
sass:
    sass_dir: _sass
    sourcemap: true

gems:
- jekyll-sitemap
- jekyll-feed
- jekyll-redirect-from