######################
# Site configuration #
######################
title: "LGBT+ Members of Parliament"
description: "A website and dataset listing the MPs in the UK House of Commons who say they are lesbian, gay, bisexual or trans or have another minority sexual orientation or gender identity (LGBT+)."
author: "John Peart"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mps.whoare.lgbt"

####################
# Feature settings #
####################
banner-mode: true
banner-mode--header: "A General Election is taking place on 4 July 2024"
banner-mode--body: |
    This dataset reflects LGBT+ MPs in the Parliament that dissolved on 30 May 2024. The dataset will be updated  with the information about the next Parliament as soon as it is available.

    **Help to update this dataset.** [Submit information about new, returning or former LGBT+ MPs](/contribute/).

# Shows a blockquote on data pages exposing some of the underlying calculations
error-check: false

analytics: true
analytics-token: "d36444326796457985d7fc75774c393e"

###############
# Asset paths #
###############
image-path: "/assets/images"
css-path: "/assets/styles"
js-path: "/assets/scripts"
social-media-image: "/assets/images/site/social-media.png"
favicon: "/favicon.ico"
favicon-svg: "/assets/images/site/favicon.svg"
favicon-pinned-svg: "/assets/images/site/favicon-pinned-svg.svg"
favicon-large-png: "/assets/images/site/favicon-large-png.png"
theme-colour: "#373151"

#######################
# <link rel="me" ...> #
#######################
# Github
github-url:  "https://github.com/johnpeart/lgbt-mp"
github-handle:  "johnpeart"

###############
# Collections #
###############

collections:
  parliaments:
    output: true
    permalink: /historic/parliament/:slug/:name
    defaults:
      values:
        layout: blog/post

##################
# Build settings #
##################
permalink: pretty
markdown: kramdown
future: false
highlighter: rouge
sass:
  sass_dir: _sass

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
